# Generated by Django 3.1.7 on 2021-03-15 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 15, 51, 33, 467144), verbose_name='添加时间'),
        ),
    ]
