# Generated by Django 3.1.7 on 2021-03-15 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_auto_20210315_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 16, 7, 13, 879133), verbose_name='添加时间'),
        ),
    ]
