# Generated by Django 3.0.5 on 2021-03-22 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acount', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_income', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_expenditure', to=settings.AUTH_USER_MODEL),
        ),
    ]
