# Generated by Django 3.1.7 on 2021-03-18 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='支出信息')),
                ('ex_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='消费时间')),
                ('ex_kind', models.CharField(choices=[(1, '教育'), (2, '餐饮'), (3, '理财'), (4, '日用'), (5, '零食'), (6, '交通'), (7, '服饰'), (8, '数码'), (9, '住房'), (10, '医疗')], max_length=8, verbose_name='消费种类')),
                ('ex_text', models.CharField(default='无', max_length=20, verbose_name='消费备注')),
            ],
            options={
                'verbose_name': '消费支出',
                'verbose_name_plural': '消费支出',
                'db_table': 'account_expenditrue',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='收入信息')),
                ('in_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='收入时间')),
                ('in_kind', models.CharField(choices=[(1, '薪资'), (2, '退款'), (3, '理财'), (4, '兼职'), (5, '还钱'), (6, '借入'), (7, '意外所得'), (8, '报销'), (9, '投资'), (10, '其他')], max_length=8, verbose_name='收入种类')),
                ('in_text', models.CharField(default='无', max_length=20, verbose_name='收入备注')),
            ],
        ),
    ]
