# Generated by Django 3.0.5 on 2021-03-22 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 22, 22, 37, 6, 903912), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 22, 22, 37, 6, 903912), verbose_name='添加时间'),
        ),
    ]
