# Generated by Django 3.0.5 on 2021-03-21 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_auto_20210321_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'managed': True, 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 21, 25, 50, 94272), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 21, 25, 50, 93288), verbose_name='添加时间'),
        ),
    ]
